services:
  mysql:
    image: mysql
    container_name: mysql-plotfail
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root

    ports:
      - "3306:3306"

    volumes:
      - ./mysql_data:/var/lib/mysql
